name: Jsonnet Lint
description: Run Jsonnet Lint
author: dadav <dadav@protonmail.com>

branding:
  icon: 'activity'
  color: 'gray-dark'

inputs:
  targets:
    description: |
      Paths to jsonnet files (i.e., .jsonnet, .libsonnet, etc..)
      or directories containing those files.
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    TARGETS: ${{ inputs.targets }}
